[build]
  publish = "."

[[redirects]]
  from = "/services"
  to = "/services/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about/index.html"
  status = 200

[[redirects]]
  from = "/crypto-tax"
  to = "/crypto-tax/index.html"
  status = 200

[[redirects]]
  from = "/airdrop-tax"
  to = "/airdrop-tax/index.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact/index.html"
  status = 200

[[redirects]]
  from = "/crypto-hack-tax"
  to = "/crypto-hack-tax/index.html"
  status = 200
